Unitoken can from background point to an existing Token and delete the current token held
MissingReferenceException: The object of type 'Unitoken' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
ArcMapLayout.AddForces (System.Collections.Generic.List`1[T] unitokens, System.Collections.Generic.List`1[T] arcs) (at Assets/Scripts/ArcMapLayout.cs:60)
ArcMapManager.UpdateMap () (at Assets/Scripts/ArcMapManager.cs:143)
ArcMapManager.Update () (at Assets/Scripts/ArcMapManager.cs:113)